'use client'
import { useEffect, useState } from 'react'
import styles from './JobHuntView.module.css'
import { PreparedApplication, type Preparation } from './PreparedApplication'
type Match = { key: string; status: string; preparation?: Preparation; job: { title: string; company: string; location: string; payment: string; url: string }; assessment: { matches: string[]; gaps: string[]; warnings: string[] } }
type State = { name: string; health: { state?: string; updated_at?: string }; shortlist: { created_at?: string; candidates: Match[] } }
async function request(action: string, body = {}) {
  const r = await fetch(`/api/job-hunt/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  if (!r.ok) throw new Error((await r.json()).error || 'Job Hunt unavailable')
  return r
}
export function JobHuntView() {
  const [data, setData] = useState<State>(), [error, setError] = useState(''), [busy, setBusy] = useState(false), [selected, setSelected] = useState<Match>(), [confirmed, setConfirmed] = useState(false)
  const load = async () => { setBusy(true); setError(''); try { setData(await (await request('state')).json()) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  useEffect(() => { void load() }, [])
  const update = async (status: string) => { if (!selected) return; setBusy(true); try { await request('status', { key: selected.key, status, confirmed }); setSelected({ ...selected, status: status === 'submitted' ? 'User marked submitted — unverified' : status }); setConfirmed(false); await load() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const download = async (filename: string) => { if (!selected) return; setBusy(true); try { const r = await request('download', { key: selected.key, filename }); const url = URL.createObjectURL(await r.blob()); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); await load() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const safeUrl = (url: string) => { try { const u = new URL(url); return u.protocol === 'https:' && !u.username && !u.password ? u.href : undefined } catch { return undefined } }
  return <section className={styles.root} aria-busy={busy}><header><h1>Job Hunt</h1><p>Your private shortlist and factual application drafts.</p><button disabled={busy} onClick={() => void load()}>Refresh view</button></header>{error && <p role="alert">{error}</p>}{busy && <p role="status">Loading…</p>}{data && <><p>{data.name} · Worker: {data.health.state || 'Unknown'} · Last shortlist: {data.shortlist.created_at ? new Date(data.shortlist.created_at).toLocaleString() : 'Not recorded'}</p><p>Complete applications on the employer’s website. Downloading a draft does not submit it.</p><div className={styles.grid}><div aria-label="Job shortlist">{!data.shortlist.candidates.length && <p>No review candidates recorded yet.</p>}{data.shortlist.candidates.map(m => <button className={styles.card} key={m.key} aria-pressed={selected?.key === m.key} onClick={() => { setSelected(m); setConfirmed(false) }}><strong>{m.job.title}</strong><span>{m.job.company} · {m.job.location}</span><span>{m.status}</span></button>)}</div><article>{!selected ? <p>Select a job to review requirements and prepare your application.</p> : <>{selected.job.url === 'https://job-boards.greenhouse.io/emergentlabsinc/jobs/4335496009' && <PreparedApplication key={selected.key} initial={selected.preparation} onPrepare={async nightShift => (await request('prepare', { key: selected.key, nightShift })).json()} />}<h2>{selected.job.title}</h2><p>{selected.job.company} · {selected.job.location}</p><p>Pay: {selected.job.payment || 'Not stated — review required'}</p><p>Status: {selected.status}</p><h3>Matched skills</h3><p>{selected.assessment.matches.join(', ') || 'None recorded'}</p><h3>Unconfirmed skills</h3><p>{selected.assessment.gaps.join(', ') || 'Read the full job description'}</p>{selected.assessment.warnings.map((w, i) => <p key={i}>{w}</p>)}<div className={styles.actions}>{safeUrl(selected.job.url) && <a href={safeUrl(selected.job.url)} target="_blank" rel="noopener noreferrer">Open employer form</a>}{['resume.txt', 'resume.html', 'application.txt'].map(f => <button key={f} disabled={busy} onClick={() => void download(f)}>Download {f}</button>)}<button disabled={busy} onClick={() => void update('saved')}>Save job</button></div><label><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /> I personally submitted on the employer’s website. This only records my claim; it does not send an application.</label><button disabled={busy || !confirmed} onClick={() => void update('submitted')}>Record my claim (does not send)</button></>}</article></div></>}</section>
}
